### ISSUE TITLE
Some Issues 

### ISSUE THREAD

**Issue by enesctnn** [Hakanlsk/weatherApp#1]
## Installation in Local
![err1](https://github.com/Hakanlsk/weatherApp/assets/135036626/5d8338c0-3844-430d-b890-6a29a97d9479)
![err2](https://github.com/Hakanlsk/weatherApp/assets/135036626/4ec3ea92-f17d-44c4-9060-27129bfdbd71)

1. Most of the dependencies is neighter deprecated nor  missing please check package.json file .

## Usage

2. Navigation is not provided so it's really hard to browse around .
3. There is no Responsive design for different screen sizes .
4. Error feedbacks on search page should disappear after some time (bad user experience) . 
5. City suggestions is not working properly. You can fix that by getting auto completion from an auto complete api .

Best Regards...

**Comment by Hakanlsk** [comment]
Can you tell me which screen size is having problems with the display. I
don't see a problem in my own tests, I tried to test it using Fastlane but
I had to test it myself because I had a problem.

I think you are referring to the lack of a back button for navigation. I
forgot that iPhones don't have a back button, I have fixed that now.

 I will fix the other problems you mentioned and send you the final version
before April 22. Thank you for your warnings.
You will take the final version into consideration when evaluating, right?
Best regards

**Comment by enesctnn** [comment]
Sorry if I caused any misunderstanding . I am not one of the juries i just downloaded your project faced some issues and wanted to help . 

##Issue description
---
Design messed after lg screensize  for me.

Thank you.

**Comment by Hakanlsk** [comment]
I see, I thought you were one of the juries, but thank you for your
feedback. So did you apply for the same internship?

Enes Çetin ***@***.***>, 18 Nis 2024 Per, 23:40 tarihinde
şunu yazdı:

**Comment by Hakanlsk** [comment]
Problems have been fixed. Thank you for your feedback.
